# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Funcy Programmer
email: denniel.joshua@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  funcyprogrammer.com is a blog about my adventures in programming.
  I program in ruby and python. I like making websites and visual novels.
  Sometimes I also try to draw thing. I still cannot accept that I don't have talent in drawing.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://funcyprogrammer.com" # the base hostname & protocol for your site
twitter_username: DIJDIAZ
github_username:  funcprog

# Build settings
markdown: kramdown

# Navigation
navigation:
  About: '/about'
  Archive: '/archive'
  feed: '/feed.xml'